src/server/CSG.WebSite/Controllers/CodeSigningToolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using CSG.AppServer.Db;
using CSG.AppServer.Entities;
using CSG.AppServer.Managers;
using CSG.AppServer.Security;
using CSG.WebSite.Helpers;
using System.Security.Cryptography.X509Certificates;
using System.DirectoryServices;

namespace CSG.WebSite.Controllers
{
    public class CodeSigningToolController : Controller
    {
        public ActionResult ManageSigningTools(string savedMessage = null)
        {
            Gatekeeper gatekeeper = new Gatekeeper();

            try
            {
                gatekeeper.ValidateUserIsAppAdmin();

                ESPDbDomainService svc = new ESPDbDomainService();
                ViewBag.CodeSigningTools = svc.GetCodeSigningTools();
                ViewBag.SavedMessage = savedMessage;

                return View();
            }
            catch (Exception e)
            {
                gatekeeper.LogException(String.Empty, e);
                return UIHelper.RedirectToError(e);
            }
        }

        
        public class CodeSigningToolInfo
        {
            public string TimestampServer { get; set; }
            public string VerificationArgs { get; set; }
            public string SigningArgs { get; set; }
            public bool IsMacroSigner { get; set; }
        }

        public JsonResult GetSigningToolInfo(int toolId)
        {

            Gatekeeper gatekeeper = new Gatekeeper();
            try
            {
                // this is only used by administrators
                gatekeeper.ValidateUserIsAppAdmin();

                CodeSigningToolInfo toolInfo = new CodeSigningToolInfo()
                {
                    TimestampServer = string.Empty,
                    VerificationArgs = string.Empty,
                    SigningArgs = string.Empty,
                    IsMacroSigner = false
                };
                ESPDbDomainService svc = new ESPDbDomainService();
                var cst = svc.GetCodeSigningToolById(toolId);

                if (cst != null)
                {
                    toolInfo.TimestampServer = cst.TimestampServer;
                    toolInfo.SigningArgs = cst.CommonSigningArguments;
                    toolInfo.VerificationArgs = cst.CommonVerificationArguments;
                    toolInfo.IsMacroSigner = cst.Offline;
                }

                var response = Json(toolInfo, JsonRequestBehavior.AllowGet);

                return response;
            }
            catch (Exception e)
            {
                gatekeeper.LogException(String.Empty, e);
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult ManageSigningTool(int toolId)
        {
            SelectListItem slTypeSigntool = new SelectListItem { Selected = false, Text = "SignTool", Value = "0" };
            SelectListItem slTypeJarsigner = new SelectListItem { Selected = false, Text = "jarsigner", Value = "1" };
            SelectListItem slTypeCodesignCommand = new SelectListItem { Selected = false, Text = "codesign", Value = "2" };
            SelectListItem slTypeCodesignSCommand = new SelectListItem { Selected = false, Text = "codesignShare", Value = "3" };
            SelectListItem slTypeHABcstCommand = new SelectListItem { Selected = false, Text = "HABcst", Value = "4" };
            SelectListItem slTypeEvmctlCommand = new SelectListItem { Selected = false, Text = "evmctl", Value = "5" };
            SelectListItem slTypeCertreqCommand = new SelectListItem { Selected = false, Text = "certreq", Value = "6" };
            SelectListItem slTypeCertreqRCommand = new SelectListItem { Selected = false, Text = "certreqRemote", Value = "7" };
            SelectListItem slTypeSignToolRCommand = new SelectListItem { Selected = false, Text = "SigntoolRemote", Value = "8" };
            SelectListItem slTypeSignBinaryCommand = new SelectListItem { Selected = false, Text = "SignBinary", Value = "9" };
            SelectListItem slTypeSnCommand = new SelectListItem { Selected = false, Text = "sn", Value = "10" };
            SelectListItem slTypeLinuxScriptCommand = new SelectListItem { Selected = false, Text = "LinuxScript", Value = "11" };
            SelectListItem slTypeSnRCommand = new SelectListItem { Selected = false, Text = "snR", Value = "12" };
            SelectListItem slTypeGenericCommand = new SelectListItem { Selected = false, Text = "Generic", Value = "13" };

            // the order of this last matters, it is indexed by the entry in the DB
            List<SelectListItem> selectListItems = new List<SelectListItem>() {
                                slTypeSigntool,                 // 0
                                slTypeJarsigner,                // 1
                                slTypeCodesignCommand,          // 2
                                slTypeCodesignSCommand,         // 3
                                slTypeHABcstCommand,            // 4
                                slTypeEvmctlCommand,           // 5
                                slTypeCertreqCommand,           // 6
                                slTypeCertreqRCommand,          // 7
                                slTypeSignToolRCommand,         // 8
                                slTypeSignBinaryCommand,     // 9
                                slTypeSnCommand,            // 10
                                slTypeLinuxScriptCommand,       // 11
                                slTypeSnRCommand,           // 12
                                slTypeGenericCommand           // 13            
                };

            Gatekeeper gatekeeper = new Gatekeeper();

            try
            {
                gatekeeper.ValidateUserIsAppAdmin();

                ESPDbDomainService svc = new ESPDbDomainService();
                CodeSigningTool tool = null;
                string selectedArgsFormat = null;

                if (toolId > 0)
                {
                    tool = svc.GetCodeSigningToolById(toolId);

                    if (tool.SigningArgumentFormat < selectListItems.Count)
                    {
                        selectedArgsFormat = selectListItems[tool.SigningArgumentFormat].Value;
                    }
                    else
                    {
                        selectedArgsFormat = selectListItems[0].Value;

                    }
                }
                else
                {
                    tool = new CodeSigningTool();
                }

                var slCommandLineTypes = new SelectList(selectListItems, "Value", "Text", selectedArgsFormat);
                ViewBag.CommandLineTypes = slCommandLineTypes;

                return View(tool);
            }
            catch (Exception e)
            {
                gatekeeper.LogException(String.Empty, e);
                return UIHelper.RedirectToError(e);
            }

        }

        [HttpPost]
        public ActionResult SaveCodeSigningTool(FormCollection collection, CodeSigningTool csTool)
        {
            Gatekeeper gatekeeper = new Gatekeeper();
            string slCommandType = collection["ddlCommandLineType"];
            int commandLineType = 0;

            try
            {
                gatekeeper.ValidateUserIsAppAdmin();

                if (csTool.Offline)
                {
                    csTool.SigningExecutable = "offline";
                    csTool.SigningArgumentFormat = 0;
                    csTool.VerificationExecutable = "offline";
                }
                else
                {
                    if (slCommandType != null)
                    {
                        commandLineType = Convert.ToInt32(slCommandType);
                        if (commandLineType < 0 || commandLineType > 13)
                        {
                            commandLineType = 0;
                        }
                    }
                    csTool.SigningArgumentFormat = commandLineType;
                }

                // log the user activity
                ActivityLog.Log(gatekeeper.GetCurrentUserProfile(),
                                ActivityLog.LogEventId_CHANGE_TOOL_CONFIG,
                                "ManageCodeSigningTool", "SaveTool",
                                csTool.Name);

                SigningToolManager manager = new SigningToolManager();
                manager.SaveCodeSigningTool(csTool);               
            }
            catch (ToolExistsException e)
            {
                return ToolExists(e.ExistingToolName);

            }
            catch (Exception e)
            {
                gatekeeper.LogException(String.Empty, e);
                return UIHelper.RedirectToError(e);
            }
            return RedirectToAction("ManageSigningTools", new { @savedMessage = "Signing Tool Saved" });
        }

        public ActionResult ToolExists(string toolName)
        {
            TempData.Add("id", toolName);
            TempData.Add("entity", "Tool");

            return RedirectToAction("EntityExists", "Admin");
        }
    }
}

src/server/CSG.WebSite/Views/CodeSigningTool/ManageCodeSigningTool.cshtml
@model ESP.AppServer.Entities.CodeSigningTool

@{
    ViewBag.Title = "Signing Tool";
}

<hgroup class="title">
    <h2>@ViewBag.Title - <font color="#000000">@Model.Name</font></h2>
    <h3>@ViewBag.Message</h3>
</hgroup>

<hr />

<script type="text/javascript">
    function Cancel() {
        window.location = "/CodeSigningTool/ManageCodeSigningTools/";
    }

</script>

@using (Html.BeginForm("SaveCodeSigningTool", "CodeSigningTool", FormMethod.Post, new { name = "SaveCodeSigningTool" }))
{ 
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


<table width="80%" id="tblCodeSigningTools">

</table>

<table width="80%">
    <tr>
        <td align="left">
            <input type="button" value="Cancel" onclick="Cancel();" />
        </td>
        <td align="right">
            <input type="submit" value="Save"/>
        </td>
    </tr>
</table>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/server/CSG.WebSite/Views/CodeSigningTool/ManageCodeSigningTools.cshtml
@{
    ViewBag.Title = "Manage Signing Tools";
}

<hgroup class="title">
    <h2>@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>

<hr />

<script type="text/javascript">
    function Edit(typeId) {
        window.location = "/CodeSigningTools/ManageCodeSigningTool/?typeId=" + typeId;
    }

</script>

<table width="100%" id="tblCodeSigningTools">
    <tr>
        <td colspan="7" align="right">
            <input type="button" value="Add New Tool" onclick="Edit(0);" />
        </td>
    </tr>
    <tr>
        <th>
            Tool Name
        </th>
        <th>
            Tool Type
        </th>
        <th>
            Tool Location
        </th>
    </tr>
    <tr>
        <td>
            signtool 32-bit
        </td>
        <td>
            SIGNTOOL
        </td>
        <td>
            C:\Program Files (x86)\Windows Kits\10\bin\x86
        </td>
    </tr>
    <tr>
        <td>
            jarsigner
        </td>
        <td>
            JARSIGNER
        </td>
        <td>
            C:\Program Files (x86)\Java
        </td>
    </tr>
    <tr>
        <td>
            generic signing tool
        </td>
        <td>
            CUSTOM
        </td>
        <td>
            C:\Program Files (x86)\Other
        </td>
    </tr>
</table>

src/server/CSG.WebSite/Views/CodeSigningTool/ManageSigningTool.cshtml
@model CSG.AppServer.Entities.CodeSigningTool

@{
    ViewBag.Title = "Signing Tool";
}

<hgroup class="title">
    <h2>@ViewBag.Title - <font color="#000000">@Model.Name</font></h2>
    <h3>@ViewBag.Message</h3>
</hgroup>

<hr />

<script type="text/javascript">
    function OfflineClick() {
        var signingArguments = document.getElementById("rwSigningArguments");
        var verifyArguments = document.getElementById("rwVerifyArguments");
        var signingConfig = document.getElementById("rwSigningConfig");
        var argType = document.getElementById("rwArgType");
        var timestampServer = document.getElementById("rwTimestampServer");

        if (document.getElementById("cbOffline").checked == true)
        {
            signingArguments.style.display = 'none';
            verifyArguments.style.display = 'none';
            signingConfig.style.display = 'none';
            argType.style.display = 'none';
            timestampServer.style.display = 'none';
        }
        else
        {
            signingArguments.style.display = 'table-row';
            verifyArguments.style.display = 'table-row';
            signingConfig.style.display = 'table-row';
            argType.style.display = 'table-row';
            timestampServer.style.display = 'table-row';
        }
    }
    function Cancel() {
        window.location = "/CodeSigningTool/ManageSigningTools/";
    }

    $(document).ready(function () {
        @{
            if (Model.Offline == true)
            {
                <text>
                    document.getElementById("rwSigningArguments").style.display = "none";
                    document.getElementById("rwVerifyArguments").style.display = "none";
                    document.getElementById("rwSigningConfig").style.display = "none";
                    document.getElementById("rwArgType").style.display = "none";
                    document.getElementById("rwTimestampServer").style.display = "none";
                </text>

            }
        }
    });
</script>

@using (Html.BeginForm("SaveCodeSigningTool", "CodeSigningTool", FormMethod.Post, new { name = "SaveCodeSigningTool" }))
{
    @Html.HiddenFor(m => m.Id)
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    <table width="80%" id="tblCodeSigningTools"></table>

    <table width="80%">
        <tr>
            <th>
                Name
            </th>
            <td>
                @Html.TextBoxFor(m => m.Name)
                @Html.ValidationMessageFor(m => m.Name)
            </td>
        </tr>
        <tr id="rwSigningArguments">
            <th>
                Additional Signing Arguments
            </th>
            <td>
                @Html.TextBoxFor(m => m.CommonSigningArguments, new { @id = "tbSigningArguments" })
                @Html.ValidationMessageFor(m => m.CommonSigningArguments)
            </td>
        </tr>
        <tr id="rwVerifyArguments">
            <th>
                Additional Verification Arguments
            </th>
            <td>
                @Html.TextBoxFor(m => m.CommonVerificationArguments, new { @id = "tbVerificationArguments" })
                @Html.ValidationMessageFor(m => m.CommonVerificationArguments)
            </td>
        </tr>
        <tr id="rwArgType">
            <th>
                Arguments Format
            </th>
            <td>
                @Html.DropDownList("ddlCommandLineType", ViewBag.CommandLineTypes as SelectList, new { @id = "slCommandLineType" })
            </td>
        </tr>
        <tr id="rwTimestampServer">
            <th>
                Timestamp Server
            </th>
            <td>
                @Html.TextBoxFor(m => m.TimestampServer)
            </td>
        </tr>

        <tr>
            <td align="left">
                <input type="button" value="Cancel" onclick="Cancel();" />
            </td>
            <td align="right">
                <input type="submit" value="Save" />
            </td>
        </tr>
    </table>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/server/CSG.WebSite/Views/CodeSigningTool/ManageSigningTools.cshtml
@{
    ViewBag.Title = "Manage Signing Tools";
}

<hgroup class="title">
    <h2>@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>

<hr />

<script type="text/javascript">
    function Edit(toolId) {
        window.location = "/CodeSigningTool/ManageSigningTool/?toolId=" + toolId;
    }

</script>

<table width="100%" id="tblCodeSigningTools">
    @{ string savedMessage = ViewBag.SavedMessage; }
    @if (savedMessage != null && savedMessage.Length > 0)
    {
        <tr>
            <td colspan="7" align="center" style="border-style:solid;border-width: 1px 1px 1px 1px;border-color: blue">
                @savedMessage
            </td>
        </tr>
    }
    <tr>
        <td colspan="7" align="right">
            <input type="button" value="Add New Tool" onclick="Edit(0);" />
        </td>
    </tr>
    <tr>
        <th>
            Tool Name
        </th>
        <th>
            Tool Type
        </th>
    </tr>
    @if (ViewBag.CodeSigningTools != null)
    {
        foreach (CSG.AppServer.Entities.CodeSigningTool tool in ViewBag.CodeSigningTools)
        {
            <tr>
                <td>
                    @tool.Name
                </td>
                <td>
                    @if (@tool.Offline == true)
                    {
                        <font>Macro</font>
                    }
                    else
                    {
                        if (@tool.SigningArgumentFormat == 0)
                        {
                            <font>signtool</font>
                        }
                        else if (@tool.SigningArgumentFormat == 1)
                        {
                            <font>jarsigner</font>
                        }
                        else if (@tool.SigningArgumentFormat == 2)
                        {
                            <font>codesign</font>
                        }
                        else if (@tool.SigningArgumentFormat == 3)
                        {
                            <font>codesignShare</font>
                        }
                        else if (@tool.SigningArgumentFormat == 4)
                        {
                            <font>HABcst</font>
                        }
                        else if (@tool.SigningArgumentFormat == 5)
                        {
                            <font>evmctl</font>
                        }
                        else if (@tool.SigningArgumentFormat == 11)
                        {
                            <font>LinuxScript</font>
                        }
                        else if (@tool.SigningArgumentFormat == 6)
                        {
                            <font>certreq</font>
                        }
                        else if (@tool.SigningArgumentFormat == 7)
                        {
                            <font>certreqRemote</font>
                        }
                        else if (@tool.SigningArgumentFormat == 8)
                        {
                            <font>signtoolRemote</font>
                        }
                        else if (@tool.SigningArgumentFormat == 9)
                        {
                            <font>SignBinary</font>
                        }
                        else if (@tool.SigningArgumentFormat == 10)
                        {
                            <font>sn</font>
                        }
                        else
                        {
                            <font>generic</font>
                        }
                    }
                </td>
                <td style="padding-left: 20px;">
                    <img alt="Edit Type" src="../../Images/details.png" height="25" width="25" onclick="Edit(@tool.Id);" />
                </td>
            </tr>
        }
    }
</table>