src/server/CSG.WebSite/Controllers/SystemSettingController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using CSG.AppServer.Db;
using CSG.AppServer.Entities;
using CSG.AppServer.Managers;
using CSG.AppServer.Security;
using CSG.WebSite.Helpers;
using CSG.WebSite.Models;

namespace CSG.WebSite.Controllers
{
    public class SystemSettingController : Controller
    {
        public ActionResult DoMaintenance()
        {
            Gatekeeper gatekeeper = new Gatekeeper();

            try
            {
                gatekeeper.ValidateUserIsAppAdmin();

                ESPDbDomainService svc = new ESPDbDomainService();
                ViewBag.Settings = svc.GetSystemSettings(null).Where(s => s.ExcludeFromSettingsUI == false).OrderBy(s => s.Name);

                return View();
            }
            catch (Exception e)
            {
                gatekeeper.LogException(String.Empty, e);
                return UIHelper.RedirectToError(e);
            }
        }

        /// <summary>
        /// Save the group
        /// </summary>
        [HttpPost]
        public ActionResult DoMaintenance(FormCollection collection)
        {
            Gatekeeper gatekeeper = new Gatekeeper();

            try
            {
                gatekeeper.ValidateUserIsAppAdmin();

                int ageOfFilesToDelete = System.Convert.ToInt32(collection["txtAgeOfFiles"]);
                ESPDbDomainService svc = new ESPDbDomainService();
                CodeSigningRequestManager mgr = new CodeSigningRequestManager();
                var recordsDeleted = mgr.ArchiveRequests(ageOfFilesToDelete);
                ViewBag.RecordsCount = recordsDeleted.ToString();

                // log the user activity
                ActivityLog.Log(gatekeeper.GetCurrentUserProfile(),
                                ActivityLog.LogEventId_MAINTENANCE,
                                "Maintenance", "FlushedFiles",
                                ageOfFilesToDelete.ToString(), recordsDeleted.ToString());


                return View("ConfirmMaintenance", recordsDeleted);
            }
            catch (Exception e)
            {
                gatekeeper.LogException(String.Empty, e);
                return UIHelper.RedirectToError(e);
            }
        }

        public ActionResult ManageSystemSettings()
        {
            Gatekeeper gatekeeper = new Gatekeeper();

            try
            {
                gatekeeper.ValidateUserIsAppAdmin();

                ESPDbDomainService svc = new ESPDbDomainService();
                ViewBag.Settings = svc.GetSystemSettings(null).Where(s => s.ExcludeFromSettingsUI == false).OrderBy(s => s.Name);

                return View();
            }
            catch (Exception e)
            {
                gatekeeper.LogException(String.Empty, e);
                return UIHelper.RedirectToError(e);
            }
        }

        public ActionResult ManageSystemSetting(int settingId, string errorMessage=null)
        {
            Gatekeeper gatekeeper = new Gatekeeper();

            try
            {
                gatekeeper.ValidateUserIsAppAdmin();

                ESPDbDomainService svc = new ESPDbDomainService();
                SystemSetting setting = new SystemSetting();

                if (settingId > 0)
                {
                    setting = svc.GetSystemSettingById(settingId);
                    ViewBag.DataTypes = UIHelper.GetSelectListForDataTypes(setting.DataTypeId);
                }
                ViewBag.ErrorMessage = errorMessage;
                return View(setting);
            }
            catch (Exception e)
            {
                gatekeeper.LogException(String.Empty, e);
                return UIHelper.RedirectToError(e);
            }
        }

        /// <summary>
        /// Save the group
        /// </summary>
        [HttpPost]
        public ActionResult SaveSetting(SystemSetting setting)
        {
            SystemSetting oldSetting = setting;
            Gatekeeper gatekeeper = new Gatekeeper();
            try
            {
                gatekeeper.ValidateUserIsAppAdmin();

                oldSetting = SystemSettingsManager.Current.GetBySettingName(setting.Name);
                if (oldSetting == null)
                {
                    var e = new Exception("Setting cannot be changed.");
                    return UIHelper.RedirectToError(e);
                }

                // log the user activity
                ActivityLog.Log(gatekeeper.GetCurrentUserProfile(),
                                ActivityLog.LogEventId_CHANGE_SYSTEM_SETTING,
                                "ManageSystemSetting", "ChangeSetting",
                                setting.Name, oldSetting.Value, setting.Value);

                //Save the updates
                if (oldSetting.Id < 1)
                {
                    var e = new Exception("Setting cannot be created in this application.");
                    return UIHelper.RedirectToError(e);
                }
                else
                {
                    SystemSettingsManager.Current.UpdateSystemSetting(setting);
                    System.Web.HttpContext.Current.Cache.Remove("plist");
                    System.Web.HttpContext.Current.Cache.Remove("rlist");
                }

                return RedirectToAction("ManageSystemSettings");
            }
            catch (InvalidSettingValue)
            {
                return RedirectToAction("ManageSystemSetting", new { @settingId = oldSetting.Id,
                                                                     @errorMessage = "Setting value is invalid." });
            }
            catch (Exception e)
            {
                gatekeeper.LogException(String.Empty, e);
                return UIHelper.RedirectToError(e);
            }
            
        }
    }
}

src/server/CSG.WebSite/Views/SystemSetting/ConfirmMaintenance.cshtml
@{
    ViewBag.Title = "System Maintenance";
}

<hgroup class="title">
    <h2>@ViewBag.Title</h2>
</hgroup>

<script type="text/javascript">
    function Cancel() {
        window.location = "/Admin/Index";
    }
</script>

@Html.AntiForgeryToken()
@Html.ValidationSummary(true)

<hr />
<br />
@{ var count = ViewBag.RecordsCount as string;<font>Files for @count requests have been purged from the system.</font>}
<br />
<table>
    <tr>
        <td align="left">
            <input type="button" value="OK" onclick="Cancel();" />
        </td>
    </tr>
</table>

src/server/CSG.WebSite/Views/SystemSetting/DoMaintenance.cshtml
@{
    ViewBag.Title = "Perform System Maintenance";
}

<hgroup class="title">
    <h2>@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>

<hr />

<script type="text/javascript">
</script>

@using (Html.BeginForm("", "SystemSetting/DoMaintenance", FormMethod.Post))
{

    <table width="100%" id="tblSettings">
        <tr>@Html.Label("Flush Files")</tr>
        <tr></tr>
        <tr>Delete files older than @Html.TextBox("txtAgeOfFiles", 30, new { @style = "width:30px" }) days</tr>
    </table>
    <table>
        <tr>
            <td>
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <input type="submit" value="Flush Files" />
            </td>
        </tr>
    </table>
}

src/server/CSG.WebSite/Views/SystemSetting/ManageSystemSetting.cshtml
@model CSG.AppServer.Entities.SystemSetting

@{
    ViewBag.Title = "Setting";
}

<hgroup class="title">
    <h2>@ViewBag.Title - <font color="#000000">@Model.Name</font></h2>
    <h3>@ViewBag.Message</h3>
</hgroup>

<hr />

<script type="text/javascript">

    function Cancel() {
        window.location = "/SystemSetting/ManageSystemSettings/";
    }

    $(document).ready(function () {

        $("#DataType").change(function () {

            dataTypes = document.getElementById('DataType');

            for (var i = 0; i < dataTypes.length; i++) {

                if (dataTypes[i].selected) {
                    dataType = dataTypes[i].value;
                }
            }

            ShowDataType(dataType);

        });

        ShowDataType("@Model.DataTypeId");
    });

    function HideDataTypes() {
        var pnlStringLabel = document.getElementById("pnlStringLabel");
        var pnlStringValue = document.getElementById("pnlStringValue");
        var pnlIntegerLabel = document.getElementById("pnlIntegerLabel");
        var pnlIntegerValue = document.getElementById("pnlIntegerValue");
        var pnlDoubleLabel = document.getElementById("pnlDoubleLabel");
        var pnlDoubleValue = document.getElementById("pnlDoubleValue");
        var pnlDateTimeLabel = document.getElementById("pnlDateTimeLabel");
        var pnlDateTimeValue = document.getElementById("pnlDateTimeValue");
        var pnlBooleanLabel = document.getElementById("pnlBooleanLabel");
        var pnlBooleanValue = document.getElementById("pnlBooleanValue");
        var pnlPasswordLabel = document.getElementById("pnlPasswordLabel");
        var pnlPasswordValue = document.getElementById("pnlPasswordValue");
        var pnlPasswordNote = document.getElementById("pnlPasswordNote");

        pnlStringLabel.style.display = "none";
        pnlStringValue.style.display = "none";
        pnlIntegerLabel.style.display = "none";
        pnlIntegerValue.style.display = "none";
        pnlDoubleLabel.style.display = "none";
        pnlDoubleValue.style.display = "none";
        pnlDateTimeLabel.style.display = "none";
        pnlDateTimeValue.style.display = "none";
        pnlBooleanLabel.style.display = "none";
        pnlBooleanValue.style.display = "none";
        pnlPasswordLabel.style.display = "none";
        pnlPasswordValue.style.display = "none";
        pnlPasswordNote.style.display = "none";
    }

    function ShowDataType(dataType) {

        HideDataTypes();

        var pnlStringLabel = document.getElementById("pnlStringLabel");
        var pnlStringValue = document.getElementById("pnlStringValue");
        var pnlIntegerLabel = document.getElementById("pnlIntegerLabel");
        var pnlIntegerValue = document.getElementById("pnlIntegerValue");
        var pnlDoubleLabel = document.getElementById("pnlDoubleLabel");
        var pnlDoubleValue = document.getElementById("pnlDoubleValue");
        var pnlDateTimeLabel = document.getElementById("pnlDateTimeLabel");
        var pnlDateTimeValue = document.getElementById("pnlDateTimeValue");
        var pnlBooleanLabel = document.getElementById("pnlBooleanLabel");
        var pnlBooleanValue = document.getElementById("pnlBooleanValue");
        var pnlPasswordLabel = document.getElementById("pnlPasswordLabel");
        var pnlPasswordValue = document.getElementById("pnlPasswordValue");
        var pnlPasswordNote = document.getElementById("pnlPasswordNote");

        switch (dataType) {

            case "1":
                pnlStringLabel.style.display = "block";
                pnlStringValue.style.display = "block";
                break;

            case "2":
                pnlIntegerLabel.style.display = "block";
                pnlIntegerValue.style.display = "block";
                break;

            case "3":
                pnlDoubleLabel.style.display = "block";
                pnlDoubleValue.style.display = "block";
                break;

            case "4":
                pnlDateTimeLabel.style.display = "block";
                pnlDateTimeValue.style.display = "block";
                break;

            case "5":
                pnlBooleanLabel.style.display = "block";
                pnlBooleanValue.style.display = "block";
                break;

            case "6":
                pnlPasswordLabel.style.display = "block";
                pnlPasswordValue.style.display = "block";
                pnlPasswordNote.style.display = "block";
                break;
        }
    }

    $(function () {
        $("#dateValue").datetimepicker({ timeFormat: "hh:mm tt" });
    });
</script>

@using (Html.BeginForm("SaveSetting", "SystemSetting", FormMethod.Post, new { name = "SaveSetting" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.DataTypeId)

    <table width="80%" id="tblSettings">
        @{ string errorMessage = ViewBag.errorMessage; }
        @if (!string.IsNullOrEmpty(errorMessage))
        {
            <tr>
                <td colspan="2" align="center" style="border-style:solid;border-width: 1px 1px 1px 1px;border-color: red">
                    @errorMessage
                </td>
            </tr>

        }
        <tr>
            <th>
                Name
            </th>
            <td>
                @Html.TextBoxFor(m => m.Name)
                @Html.ValidationMessageFor(m => m.Name)
            </td>
        </tr>
        <tr>
            <th>
                Description
            </th>
            <td>
                @Html.TextAreaFor(m => m.Description)
                @Html.ValidationMessageFor(m => m.Description)
            </td>
        </tr>
        <tr>
            <th>
                <div id="pnlStringLabel">
                    String Value
                </div>
            </th>
            <td>
                <div id="pnlStringValue">
                    @Html.TextAreaFor(m => m.StringValue)
                </div>
            </td>
        </tr>
        <tr>
            <th>
                <div id="pnlIntegerLabel">
                    Integer Value
                </div>
            </th>
            <td>
                <div id="pnlIntegerValue">
                    @Html.TextBoxFor(m => m.IntegerValue)
                </div>
            </td>
        </tr>
        <tr>
            <th>
                <div id="pnlDoubleLabel">
                    Double Value
                </div>
            </th>
            <td>
                <div id="pnlDoubleValue">
                    @Html.TextBoxFor(m => m.DoubleValue)
                </div>
            </td>
        </tr>
        <tr>
            <th>
                <div id="pnlDateTimeLabel">
                    Date/Time Value
                </div>
            </th>
            <td>
                <div id="pnlDateTimeValue">
                    @Html.TextBoxFor(m => m.DateValue, new { id = "dateValue" })
                </div>
            </td>
        </tr>
        <tr>
            <th>
                <div id="pnlBooleanLabel">
                    Boolean Value
                </div>
            </th>
            <td>
                <div id="pnlBooleanValue">
                    @Html.CheckBoxFor(m => m.NotNullableBooleanValue, new { id = "booleanValue" })
                </div>
            </td>
        </tr>
        <tr>
            <th>
                <div id="pnlPasswordLabel">
                    Password Value
                </div>
            </th>
            <td>
                <div id="pnlPasswordValue">
                    @Html.TextBoxFor(m => m.PasswordValue)
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <div id="pnlPasswordNote">
                    The password value will be encrypted and stored in the database.  If you need to modify the value, enter the unencrypted value.  When subsequently viewing the value, it will be in it's encrypted form.
                </div>
            </td>
        </tr>
    </table>

    <table width="80%">
        <tr>
            <td align="left">
                <input type="button" value="Cancel" onclick="Cancel();" />
            </td>
            <td align="right">
                <input type="submit" value="Save" />
            </td>
        </tr>
    </table>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/Content/themes/base/css")

}

src/server/CSG.WebSite/Views/SystemSetting/ManageSystemSettings.cshtml
@{
    ViewBag.Title = "Manage System Settings";
}

<hgroup class="title">
    <h2>@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>

<hr />

<script type="text/javascript">
    function Edit(settingId) {
        window.location = "/SystemSetting/ManageSystemSetting/?settingId=" + settingId;
    }

</script>

<table width="100%" id="tblSettings">
    @*<tr>
        <td colspan="4" align="right">
            <input type="button" value="Create New Setting" onclick="Edit(0);" />
        </td>
    </tr>*@

    <tr>
        <th>
            Name
        </th>
        <th>
            Description
        </th>
        <th>
            Value
        </th>
        <th>
        </th>
    </tr>
    @if (ViewBag.Settings != null)
    {
        foreach (CSG.AppServer.Entities.SystemSetting setting in ViewBag.Settings)
        {
        if (setting.Name.Contains("OAuth") || setting.Name.Contains("GES")) { continue; }
        <tr>
            <td>@setting.Name
            </td>
            <td>@setting.Description
            </td>
            @if (setting.DataType == CSG.AppServer.SystemSettingDataType.String)
            { 
                <td>
                    @Html.TextBox("txtStringValue", setting.StringValue, new { @readonly = "readonly" })
                </td>
            }
            else if (setting.DataType == CSG.AppServer.SystemSettingDataType.Integer)
            { 
                <td>
                    @Html.TextBox("txtIntegerValue", setting.IntegerValue, new { @readonly = "readonly" })
                </td>
            }
            else if (setting.DataType == CSG.AppServer.SystemSettingDataType.Double)
            { 
                <td>
                    @Html.TextBox("txtDoubleValue", setting.DoubleValue, new { @readonly = "readonly" })
                </td>
            }
            else if (setting.DataType == CSG.AppServer.SystemSettingDataType.DateTime)
            { 
                <td>
                    @Html.TextBox("txtDateValue", setting.DateValue, new { @readonly = "readonly" })
                </td>
            }
            else if (setting.DataType == CSG.AppServer.SystemSettingDataType.Boolean)
            { 
                <td>
                    @Html.TextBox("txtBooleanValue", setting.BooleanValue, new { @readonly = "readonly" })
                </td>
            }
            else if (setting.DataType == CSG.AppServer.SystemSettingDataType.Password)
            { 
                <td>
                    @Html.TextBox("txtPasswordValue", setting.PasswordValue, new { @readonly = "readonly" })
                </td>
            }
            <td>
                <img alt="Edit Group" src="../../Images/details.png" height="25px" width="25px" onclick="Edit(@setting.Id);" />
            </td>
        </tr>
        }
    }
</table>

src/server/CSG.WebSite/Views/SystemSetting/ManageSystemSettings2.cshtml
@{
    ViewBag.Title = "Manage System Settings";
}

<hgroup class="title">
    <h2>@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>

<hr />

<script type="text/javascript">
    function Edit(settingId) {
        window.location = "/SystemSetting/ManageSystemSetting/?settingId=" + settingId;
    }

</script>

<table width="100%" id="tblSettings">
    @*<tr>
        <td colspan="4" align="right">
            <input type="button" value="Create New Setting" onclick="Edit(0);" />
        </td>
    </tr>*@

    <tr>
        <th>
            Name
        </th>
        <th>
            Description
        </th>
        <th>
            Value
        </th>
        <th>
        </th>
    </tr>
    @if (ViewBag.Settings != null)
    {
        foreach (ESP.AppServer.Entities.SystemSetting setting in ViewBag.Settings)
        { 
        <tr>
            <td>@setting.Name
            </td>
            <td>@setting.Description
            </td>
            @if (setting.DataType == ESP.AppServer.SystemSettingDataType.String)
            { 
                <td>
                    @Html.TextBox("txtStringValue", setting.StringValue, new { @readonly = "readonly" })
                </td>
            }
            else if (setting.DataType == ESP.AppServer.SystemSettingDataType.Integer)
            { 
                <td>
                    @Html.TextBox("txtIntegerValue", setting.IntegerValue, new { @readonly = "readonly" })
                </td>
            }
            else if (setting.DataType == ESP.AppServer.SystemSettingDataType.Double)
            { 
                <td>
                    @Html.TextBox("txtDoubleValue", setting.DoubleValue, new { @readonly = "readonly" })
                </td>
            }
            else if (setting.DataType == ESP.AppServer.SystemSettingDataType.DateTime)
            { 
                <td>
                    @Html.TextBox("txtDateValue", setting.DateValue, new { @readonly = "readonly" })
                </td>
            }
            else if (setting.DataType == ESP.AppServer.SystemSettingDataType.Boolean)
            { 
                <td>
                    @Html.TextBox("txtBooleanValue", setting.BooleanValue, new { @readonly = "readonly" })
                </td>
            }
            else if (setting.DataType == ESP.AppServer.SystemSettingDataType.Password)
            { 
                <td>
                    @Html.TextBox("txtPasswordValue", setting.PasswordValue, new { @readonly = "readonly" })
                </td>
            }
            <td>
                <img alt="Edit Group" src="../../Images/details.png" height="25px" width="25px" onclick="Edit(@setting.Id);" />
            </td>
        </tr>
        }
    }
</table>