src/server/CSG.WebSite/Controllers/CodeSigningRequestController.cs
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Web.Routing;
using CSG.AppServer;
using CSG.AppServer.Db;
using CSG.AppServer.Entities;
using CSG.AppServer.Managers;
using CSG.AppServer.Security;
using CSG.WebSite.Helpers;
using System.Collections.Generic;

namespace CSG.WebSite.Controllers
{
    public class CodeSigningRequestController : Controller
    {
        private static readonly ESPLogWrapper.ILog log = ESPLogWrapper.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        /// <summary>
        /// This action will allow the user to view the details of a code signing request provided they are a member the development group that
        /// submitted the request
        /// </summary>
        /// 
        public ActionResult Details(int requestId, string isFromDashboard = "false", string offline = "false")
        {
            Gatekeeper gatekeeper = new Gatekeeper();
            Dictionary<string, string> unsignedFilesAndHashes = new Dictionary<string, string>();
            Dictionary<string, string> signedFilesAndHashes = new Dictionary<string, string>();
            bool offlineSign;

            try
            {
                gatekeeper.ValidateUserViewRequest(requestId);

                CSG.AppServer.Db.ESPDbDomainService svc = new AppServer.Db.ESPDbDomainService();
                CodeSigningRequest request = svc.GetCodeSigningRequestById(requestId, "CreatedByUser, CodeSigningType");

                ViewBag.unsignedFilesAndHashes = CodeSigningRequestManager.GetNameAndHashValues(request.UnsignedFileName, request.UnsignedFileHash);

                ViewBag.IsFromDashboard = Boolean.Parse(isFromDashboard);
                ViewBag.IsEligibleForEscalation = false;
                if (request.EscalationCount == null || request.EscalationCount == 0)
                {
                    if (request.CreatedByUserId == gatekeeper.GetCurrentUserProfile().Id &&
                       (request.Status == CodeSigningRequestStatus.PartiallyApproved ||
                        request.Status == CodeSigningRequestStatus.Submitted))
                    {
                        ViewBag.IsEligibleForEscalation = true;
                    }
                }

                ViewBag.ApprovingUsers = null;
                if (request.Status == CodeSigningRequestStatus.Submitted ||
                    request.Status == CodeSigningRequestStatus.PartiallyApproved)
                {
                    List<int> profileIds;
                    List<UserProfile> approvingUsers = new List<UserProfile>();
                    List<string> approvingUserFormattedList = new List<string>();

                    if (request.CodeSigningType.AllowApprover1Approval && request.Approver1ResponderId == null)
                    {
                        // get the names of the other users in the group
                        profileIds = svc.GetUserProfileGroups().Where(m => m.GroupId == request.GroupId).Select(g => g.UserProfileId).ToList();
                        if (request.CreatedByUserId.HasValue)
                        {
                            profileIds.Remove(request.CreatedByUserId.Value);
                        }
                        approvingUsers = svc.GetUserProfiles().Where(m => profileIds.Contains(m.Id)).ToList();
                    }

                    if (request.CodeSigningType.AllowApprover2Approval && request.Approver2ResponderId == null)
                    {
                        // get the approver names
                        profileIds = svc.GetCodeSigningTypeGroups().Where(m => m.CodeSigningTypeId == request.CodeSigningTypeId &&
                                                                        m.IsApprover == true).
                                                                      Select(m => m.GroupId).ToList();
                        profileIds = svc.GetUserProfileGroups().Where(m => profileIds.Contains(m.GroupId)).Select(g => g.UserProfileId).ToList();

                        approvingUsers.AddRange(svc.GetUserProfiles().Where(m => profileIds.Contains(m.Id)));
                    }

                    foreach (var profile in approvingUsers)
                    {
                        if (!string.IsNullOrEmpty(profile.Email))
                        {
                            approvingUserFormattedList.Add(string.Format("{0}, ({1})", profile.DisplayName, profile.Email));
                        }
                        else
                        {
                            approvingUserFormattedList.Add(string.Format("{0}", profile.DisplayName));
                        }
                    }
                    ViewBag.ApprovingUsers = approvingUserFormattedList;
                }
                offlineSign = Boolean.Parse(offline);

                if (offlineSign)
                {
                    return View("Offline", request);
                }
                else
                {
                    ViewBag.signedFilesAndHashes = CodeSigningRequestManager.GetNameAndHashValues(request.SignedFileName, request.SignedFileHash);
                    return View("Details", request);
                }


            }
            catch (Exception e)
            {
                gatekeeper.LogException(String.Empty, e);
                return UIHelper.RedirectToError(e);
            }
        }

        public ActionResult Approve(int requestId)
        {
            SelectListItem slNoDays = new SelectListItem { Selected = true, Text = "None", Value = "0" };
            SelectListItem slOneDay = new SelectListItem { Selected = true, Text = "One Day", Value = "1" };
            SelectListItem slThreeDays = new SelectListItem { Selected = true, Text = "Three Days", Value = "3" };
            SelectListItem slSevenDays = new SelectListItem { Selected = true, Text = "Seven Days", Value = "7" };
            SelectListItem slThirtyDays = new SelectListItem { Selected = true, Text = "Thirty Days", Value = "30" };
            SelectListItem slSixMonths = new SelectListItem { Selected = true, Text = "Six Months", Value = "182" };
            List<SelectListItem> selectListItems = new List<SelectListItem>() { slNoDays, slOneDay, slThreeDays, slSevenDays, slThirtyDays, slSixMonths };
            var slApprovalWindows = new SelectList(selectListItems, "Value", "Text", "NoDays");
            ViewData.Add("approvalWindows", slApprovalWindows);

            CSG.AppServer.Db.ESPDbDomainService svc = new AppServer.Db.ESPDbDomainService();
            CodeSigningRequest request = svc.GetCodeSigningRequestById(requestId, "CreatedByUser, CodeSigningType");
            ViewBag.CodeSigningTypeName = request.CodeSigningType.Name;

            return View("Approve", request);
        }

        /// <summary>
        /// This action will allow the user to create a new code signing request provided they are a developer in the group selected.
        /// </summary>
        public ActionResult Create(int groupId, int codeSigningTypeId = -1, string errorMessage = null, string projectName = null)
        {
            Gatekeeper gatekeeper = new Gatekeeper();

            try
            {
                gatekeeper.ValidateUserDeveloperInGroup(groupId);

                CodeSigningRequest csRequest = new CodeSigningRequest();
                csRequest.GroupId = groupId;
                csRequest.ProjectName = projectName;
                if (codeSigningTypeId > 0)
                {
                    csRequest.CodeSigningTypeId = codeSigningTypeId;
                }

                ViewBag.Groups = new SelectList(gatekeeper.GetCurrentUserProfile().Groups
                                                                .Select(upg => upg.Group)
                                                                .Where(g => g.IsDeleted == false)
                                                                .AsEnumerable(), "Id", "Name", groupId);

                ViewBag.CodeSigningTypes = UIHelper.GetSelectList(new SelectList(Group.GetCodeSigningTypes(groupId)
                                                                                        .Where(t => t.IsDeleted == false), "Id", "Name", codeSigningTypeId), true, codeSigningTypeId);

                if (!string.IsNullOrWhiteSpace(errorMessage))
                {
                    ModelState.AddModelError("", errorMessage);
                }

                ViewBag.projectList = getProjectList();
                ViewBag.releaseList = getReleaseList();

                return View("Create", csRequest);
            }
            catch (Exception e)
            {
                gatekeeper.LogException(String.Empty, e);
                return UIHelper.RedirectToError(e);
            }
        }

        private List<string> getProjectList()
        {
            List<string> list = (List<string>)System.Web.HttpContext.Current.Cache.Get("plist");
            if ( list == null)
            {
                list= AppServerContext.ProjectList.Split(',').ToList();
                System.Web.HttpContext.Current.Cache.Insert("plist", list, null, System.Web.Caching.Cache.NoAbsoluteExpiration, TimeSpan.FromMinutes(5));
            }

            return list;
        }

        private List<string> getReleaseList()
        {
            List<string> list = (List<string>)System.Web.HttpContext.Current.Cache.Get("rlist");
            if (list == null)
            {
                list = AppServerContext.ReleaseList.Split(',').ToList();
                System.Web.HttpContext.Current.Cache.Insert("rlist", list, null, System.Web.Caching.Cache.NoAbsoluteExpiration, TimeSpan.FromMinutes(5));
            }
            return list;
        }


        public class SelectedProfileInfo
        {
            public string MetadataField1Label;
            public string MetadataField2Label;
            public string fileExtensions;
        }

src/server/CSG.WebSite/Views/CodeSigningRequest/Approve.cshtml
@model CSG.AppServer.Entities.CodeSigningRequest

@{
    ViewBag.Title = "Approve Code Signing Request";
}

<hgroup class="title">
    <h2>@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>

<hr />

<section id="approveRequestForm">
    @using (Html.BeginForm("ApproveOrDeny", "CodeSigningRequest"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        @Html.Hidden("hdnRequestId", Model.Id)

        <script type="text/javascript">
        function Cancel() {
            window.location = "/Home/Dashboard/";
        }
        function RadioClick(approveOrDeny) {
            var ddlApprovalWindow = document.getElementById("ddlApprovalWindow");
            var cbMatchFilename = document.getElementById("cbApprovalWindowMatchFilename");
            var divResponderNote = document.getElementById("reasonRow");
            if (approveOrDeny == "Deny") {
                divResponderNote.style.display = "block";
                cbMatchFilename.setAttribute("disabled","disabled");
                ddlApprovalWindow.setAttribute("disabled", "disabled");
            } else {
                divResponderNote.style.display = "none";
                cbMatchFilename.removeAttribute("disabled");
                ddlApprovalWindow.removeAttribute("disabled");
            }

        }

        $(document).ready(function () {
            document.getElementById("cbApprovalWindowMatchFilename").setAttribute("disabled", "disabled");
            document.getElementById("ddlApprovalWindow").setAttribute("disabled", "disabled");
        });
        </script>

        <fieldset>

            <ol class="round">
                <li class="one">
                    @Html.Label("Signing Request Details")
                    <br />
                    <table width="100%" id="tblPendingRequests">
                        <tr><td>@Html.Label("Request Id:")</td><td>@Model.Id</td></tr>
                        <tr><td>@Html.Label("Code Signing Profile:")</td><td>@ViewBag.CodeSigningTypeName</td></tr>
                        <tr><td>@Html.Label("Requesting User:")</td><td>@Model.CreatedByUser.DisplayName</td></tr>
                        <tr><td>@Html.Label("Submitted Time:")</td><td>@Model.CreatedDate</td></tr>
                        <tr><td>@Html.Label("File Hash:")</td><td>@Model.UnsignedFileHash</td></tr>
                        <tr><td>@Html.Label("Project Name:")</td><td>@Model.ProjectName</td></tr>
                        <tr><td>@Html.Label("Release Name:")</td><td>@Model.ReleaseName</td></tr>
                        <tr><td>@Html.Label("Code Signing Profile:")</td><td>@ViewBag.CodeSigningTypeName</td></tr>
                    </table>
                </li>

                <li class="two">
                    @Html.Label("Approve or Deny the request")
                    <br />
                    <table width="75%" id="tblPendingRequests">
                        <tr><td width="30%">@Html.Label("Approve:")</td><td><input type="radio" name="rbApproveDeny" onclick="RadioClick(this.value)" value="Approve" style='width: auto; background:#e2e2e2;border:none'></td></tr>
                        <tr><td width="30%">@Html.Label("Deny:")</td><td><input type="radio" name="rbApproveDeny" onclick="RadioClick(this.value)" checked="checked" value="Deny" style='width: auto; background:#e2e2e2;border:none'> </td></tr>
                    </table>
                    <table id="reasonRow" width="75%">
                        <tr><td width="30%">@Html.Label("Reason for denial:")</td><td>@Html.TextBox("tbDenyReason")</td></tr>
                    </table>

                </li>

                <li class="three">
                    @Html.Label("Specify an approval window for this user")
                    <br />
                    <table width="100%">
                        <tr><td width="30%">@Html.Label("Request Approval Window:")</td> <td> @Html.DropDownList("ddlApprovalWindow", ViewData["approvalWindows"] as SelectList, new { @id = "ddlApprovalWindow", @style = "width:50%" })</td></tr>
                    </table>
                    <table width="100%">
                        <tr><td width="30%">@Html.Label("Require Matching Filename: ")</td><td>@Html.CheckBox("cbRequireFilenameMatch", true, new { @id = "cbApprovalWindowMatchFilename", @style = "width:50%" })</td></tr>
                        <tr></tr>
                        <tr><td colspan="2">The Approval Window is a time period whereby you are approving furture requests from this user for this Signing Profile.</td></tr>
                    </table>

                </li>

                <li class="four">
                    @Html.Label("Submit your approval response:")
                    <br />
                    <table width="350px">
                        <tr>
                            <td><input type="button" value="Cancel" onclick="Cancel();" /></td>
                            <td align="right"><button type="submit" Name="ApproveDenyRequestId" value=@Model.Id>Submit</button></td>
                        </tr>
                    </table>

                </li>
            </ol>

        </fieldset>
    }
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/server/CSG.WebSite/Views/CodeSigningRequest/Confirm.cshtml
@model CSG.AppServer.Entities.CodeSigningRequest
@{
    ViewBag.Title = "Confirm Code Signing Request";
}

<hgroup class="title">
    <h2>@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>

<hr />

@Html.Label("Are you sure you want to submit the file for signing?")

<br />

<table>
    <tr>
        <td>
            @Html.Label("Code Signing Profile:")
    </td>
    <td>
        @Model.CodeSigningType.Name
</td>
</tr>
@{
    var unsignedFiles = ViewBag.unsignedFilesAndHashes as Dictionary<string, string>;

    foreach (KeyValuePair<String, String> fileAndHash in unsignedFiles)
    {
        <tr>
            <th>
            </th>
            <th>
                Filename
            </th>
            <th>
                SHA256 Hash
            </th>
        </tr>
            <tr>
                <td>
                    File:
                </td>
                <td>
                    @fileAndHash.Key
                </td>
                <td>
                    @fileAndHash.Value
                </td>
            </tr>
    }
}
<tr>
    <td>
        @Html.LabelFor(m => m.ReleaseName)
    </td>
    <td>
        @Model.ReleaseName
</td>
</tr>
    <tr>
        <td>
            @Html.LabelFor(m => m.ProjectName)
        </td>
        <td>
            @Model.ProjectName
        </td>
    </tr>

    </tr>

<tr><td colspan="2">&nbsp;</td></tr>
<tr>
    @if (Model.CodeSigningType.IsAutoSign)
    {
        <td colspan="2">This request does not require approval and will be auto signed.</td>
    }
    else
    {
        <td colspan="2">This request requires additional approval before it will be signed.</td>
    }
</tr>

</table>
<table>
    <tr>
        <td>
            @using (Html.BeginForm("", "CodeSigningRequest/Cancel", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                @Html.Hidden("hdnCSRequstIdCancel", Model.Id)

                <input type="submit" value="Cancel" />
            }
        </td>
        <td>
            @using (Html.BeginForm("", "CodeSigningRequest/Confirm", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <!-- Storing ids -->
                @Html.Hidden("hdnCSRequstIdConfirm", Model.Id)

                <input type="submit" value="Confirm" />
            }
        </td>
    </tr>
</table>

src/server/CSG.WebSite/Views/CodeSigningRequest/ConfirmOffline.cshtml
@model CSG.AppServer.Entities.CodeSigningRequest
@{
    ViewBag.Title = "Confirm Offline Signing Fulfillment";
}

<hgroup class="title">
    <h2>@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>

<hr />

@Html.Label("Are you sure you want to submit the signed file?")

<br />
<table>
<tr>
    <td>
        @Html.Label("Code Signing Profile:")
</td>
<td>
    @Model.CodeSigningType.Name
</td>
</tr>
@{
    var signedFiles = ViewBag.signedFilesAndHashes as Dictionary<string, string>;

    foreach (KeyValuePair<String, String> fileAndHash in signedFiles)
    {
        <tr>
            <th>
            </th>
            <th>
                Filename
            </th>
            <th>
                SHA256 Hash
            </th>
        </tr>
        <tr>
            <td>
                File:
            </td>
            <td>
                @fileAndHash.Key
            </td>
            <td>
                @fileAndHash.Value
            </td>
        </tr>
    }
}


</table>
<table>
    <tr>
        <td>
             
            @using (Html.BeginForm("", "CodeSigningRequest/CancelOffline", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                @Html.Hidden("hdnCSRequstIdCancel", Model.Id)

                <input type="submit" value="Cancel" />
            }
        </td>
        <td>
            @using (Html.BeginForm("", "CodeSigningRequest/ConfirmOffline", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <!-- Storing ids -->
                @Html.Hidden("hdnCSRequstIdConfirm", Model.Id)

                <input type="submit" value="Confirm" />
            }
        </td>
    </tr>
</table>

src/server/CSG.WebSite/Views/CodeSigningRequest/Create.cshtml
@model CSG.AppServer.Entities.CodeSigningRequest

@{
    ViewBag.Title = "Create Code Signing Request";
}

<hgroup class="title">
    <h2>@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>

<hr />

<section id="createRequestForm">
    @using (Html.BeginForm("", "CodeSigningRequest/Create", FormMethod.Post, new { name = "CodeSigningRequest/Create", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <script type="text/javascript">
        function ProfileChange() {
            var slProfile = document.getElementById("slProfile");
            var profileId = slProfile.options[slProfile.selectedIndex].value;
            $.getJSON("/CodeSigningRequest/GetProfileInfo/?typeId=" + profileId, function (data) {
                if (data.fileExtensions != null)
                {
                    document.getElementById("lblFileExtensions").style.display = 'block';
                    document.getElementById("lblFileExtensions").innerHTML = data.fileExtensions;
                }
                else
                {
                    document.getElementById("lblFileExtensions").style.display = 'none';
                }
            });
        }

        function Cancel() {
            window.location = "/Home/Dashboard/";
        }

        $(document).ready(function () {

            ProfileChange();
        });
        </script>

        <fieldset>

            <ol class="round">
                <li class="one">
                    @Html.LabelFor(m => m.Group)
                    <br />
                    @Html.DropDownListFor(m => m.GroupId, (SelectList)ViewBag.Groups)
                    @Html.ValidationMessageFor(m => m.Group, "The development group is required.")
                </li>
                <li class="two">
                    @Html.LabelFor(m => m.CodeSigningType)
                    <br />
                    @Html.DropDownListFor(m => m.CodeSigningTypeId, (SelectList)ViewBag.CodeSigningTypes)
                    @Html.ValidationMessageFor(m => m.CodeSigningTypeId, "The code signing type is required.")
                </li>
                <li class="three">
                    @Html.Label("Select the file, or archive of files, to be uploaded and signed (required):", new { style = "color:red" })
                    <br />
                    @Html.Label("", "Use a zip file to submit mutiple files. All files must be compatible with the Signing Profile.")
                    <br />
                    @Html.Label("(All submitted files must be of type: exe, ocx)", new { @id = "lblFileExtensions" })
                    <br />
                    @Html.TextBoxFor(m => m.UnsignedFileName, new { type = "file" })
                    @*<input type="file" name="SelectedFile" id="SelectedFile" class="fileSelectionDialog" data-val="true" data-val-required="The file is required."/>*@
                    @Html.ValidationMessageFor(m => m.UnsignedFileName, "The file is required")
                </li>
                <li class="four">
                    @Html.Label("Enter a project name (if desired):")
                    <br />
                    @Html.DropDownListFor(m => m.ProjectName, new SelectList(ViewBag.projectList), "Select project")
                    <br />
                    <br />
                    @Html.Label("Enter a release name (if desired):")
                    <br />
                    @Html.DropDownListFor(m => m.ReleaseName, new SelectList( ViewBag.releaseList), "Select release")
                </li>

                <li class="five">
                    @Html.Label("Submit the file for approval and signing:")
                    <br />
                    <table width="350px">
                        <tr>
                            <td><input type="button" value="Cancel" onclick="Cancel();" /></td>
                            <td align="right"><input type="submit" value="Submit" /></td>
                        </tr>
                    </table>

                </li>
            </ol>

        </fieldset>
    }
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/server/CSG.WebSite/Views/CodeSigningRequest/DownloadFile.cshtml
@{
    ViewBag.Title = "Download";
}

<hgroup class="title">
    <h2>@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>

<hr />

@if (String.IsNullOrWhiteSpace(ViewBag.ErrorMessage))
{
    Response.Clear();
    Response.AddHeader("Content-Disposition", "attachment; filename=" + ViewBag.FileToDownload.Name);
    Response.AddHeader("Content-Length", ViewBag.FileToDownload.Length.ToString());
    Response.ContentType = "application/octet-stream";

    Response.WriteFile(ViewBag.FileToDownload.FullName);
    Response.Flush();
    Response.End();
    File.Delete(ViewBag.FileToDownload.FullName);
    Directory.Delete(Path.GetDirectoryName(ViewBag.FileToDownload.FullName));

}

@ViewBag.ErrorMessage

    

src/server/CSG.WebSite/Views/CodeSigningRequest/FulfillOffline.cshtml
@{
    ViewBag.Title = "Fulfill Offline Request";
    ViewBag.Message = "Upload the signed file.";
}


<hgroup class="title">
    <h2>@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>

<hr />

<script type="text/javascript">
    function Cancel() {
        window.location = "/Home/Index";
    }

</script>
@using (Html.BeginForm("FulfillOffline", "CodeSigningRequest", FormMethod.Post, new { name = "FulfillOffline", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.Hidden("hdnRequestId", ViewBag.RequestId as string)

    <table width="80%">
        @{ string errorMessage = ViewBag.errorMessage; }
        @if (!string.IsNullOrEmpty(errorMessage))
        {
            <tr>
                <td colspan="2" align="center" style="border-style:solid;border-width: 1px 1px 1px 1px;border-color: red">
                    @errorMessage
                </td>
            </tr>

        }

        <tr>
            <td align="center">
                @Html.Label("Signed File:")
            </td>
            <td>
                <input type="file" name="SignedFile" id="SignedFile" data-val="true" data-val-required="The file is required." />
            </td>
        </tr>
    </table>
    <table width="80%">
        <tr>
            <td align="left">
                <input type="button" value="Cancel" onclick="Cancel();" />
            </td>
            <td align="right">
                <input type="submit" value="Fulfill Request" />
            </td>
        </tr>
    </table>
            }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/server/CSG.WebSite/Views/CodeSigningRequest/Output.cshtml
<hgroup class="title">
    <h2>@ViewBag.Title</h2>
</hgroup>

<hr />

@ViewBag.Message

<br />

<table>
    <tr>
        <td>
            @using (Html.BeginForm("Dashboard", "Home", FormMethod.Get))
            {
                <input type="submit" value="Return To Dashboard" />
            }
        </td>
        <td>
            @if (ViewBag.IncludeCreateAnotherButton)
            {
                using (Html.BeginForm("Output", "CodeSigningRequest", FormMethod.Post))
                {
                    <input type="hidden" id="hdnGroupId" name="hdnGroupId" value="@ViewBag.GroupId" />
                    <input type="submit" value="Create another request" />
                }
            }
        </td>
    </tr>
</table>